
before_install:
  - 'sudo apt-get update'
#  - 'git config --global user.email "cf-bosh-eng+bosh-ci-push-pull@pivotallabs.com"'
#  - 'git config --global user.name "BOSH CI Push Pull"'

install:
  - 'sudo apt-get install dnsutils'
  - 'bundle install --local --without development'

rvm:
  - ruby-2.1.2

script: 'bosh create release --force'
#script: 'bundle exec rake --trace go $TASKS'

env:

addons:
  code_climate:
