---
platform: linux
image: docker:///boshcpi/openstack-cpi-release
inputs:
  - name: bosh-cpi-release
  - name: version-semver
outputs:
  - name: bosh-release
run:
  path: bosh-cpi-release/ci/tasks/build-candidate.sh
