---
platform: linux
image: docker:///boshcpi/cloudstack-cpi-release
inputs:
  - name: bosh-cpi-release       # --- location of task script to run
  - name: bosh-init              # --- bosh-init executable to do deploy
  - name: director-state-file    # --- repository to get and store deployment state file
  - name: bosh-release           # -\
  - name: bosh-cpi-dev-artifacts # -++ used for deployment manifest referenced by manifest_path
  - name: version-semver         # -//
  - name: stemcell               # -/
run:
  path: bosh-cpi-release/ci/tasks/deploy-manual-networking.sh
params:
  base_os:                       replace-me
  network_type_to_test:          replace-me
  cloudstack_flavor:              replace-me
  cloudstack_connection_timeout:  replace-me
  cloudstack_read_timeout:        replace-me
  cloudstack_write_timeout:       replace-me
  cloudstack_state_timeout:       replace-me
  private_key_data:              replace-me
  bosh_registry_port:            replace-me
  cloudstack_net_id:              replace-me
  cloudstack_security_group:      replace-me
  cloudstack_default_key_name:    replace-me
  cloudstack_auth_url:            replace-me
  cloudstack_username:            replace-me
  cloudstack_api_key:             replace-me
  cloudstack_tenant:              replace-me
  cloudstack_floating_ip:         replace-me
  cloudstack_manual_ip:           replace-me
  cloudstack_net_cidr:            replace-me
  cloudstack_net_gateway:         replace-me
