---
platform: linux
image: docker:///boshcpi/openstack-cpi-release
inputs:
  - name: bosh-cpi-release       # --- location of task script to run
  - name: director-state-file    # --- repository to get and store deployment state file
  - name: bosh-init              # --- bosh-init executable to do deploy
  - name: bosh-release           # -\
  - name: bosh-cpi-dev-artifacts # -++ used for deployment manifest referenced by manifest_path
  - name: version-semver         # -//
  - name: stemcell               # -/
run:
  path: bosh-cpi-release/ci/tasks/deploy-dynamic-networking.sh
params:
  base_os:                       replace-me
  network_type_to_test:          replace-me
  openstack_flavor:              replace-me
  openstack_connection_timeout:  replace-me
  openstack_read_timeout:        replace-me
  openstack_write_timeout:       replace-me
  openstack_state_timeout:       replace-me
  private_key_data:              replace-me
  bosh_registry_port:            replace-me
  openstack_net_id:              replace-me
  openstack_security_group:      replace-me
  openstack_default_key_name:    replace-me
  openstack_auth_url:            replace-me
  openstack_username:            replace-me
  openstack_api_key:             replace-me
  openstack_tenant:              replace-me
  openstack_floating_ip:         replace-me
