---
platform: linux
image: docker:///boshcpi/openstack-cpi-release
inputs:
- name: bosh-cpi-release
run:
  path: bosh-cpi-release/ci/tasks/run-lifecycle.sh
params:
  BOSH_CLOUDSTACK_AUTH_URL:            replace-me
  BOSH_CLOUDSTACK_USERNAME:            replace-me
  BOSH_CLOUDSTACK_API_KEY:             replace-me
  BOSH_CLOUDSTACK_TENANT:              replace-me
  BOSH_CLOUDSTACK_MANUAL_IP:           replace-me
  BOSH_CLOUDSTACK_NET_ID:              replace-me
  BOSH_CLOUDSTACK_STEMCELL_ID:         replace-me
  BOSH_CLI_SILENCE_SLOW_LOAD_WARNING: replace-me
  BOSH_CLOUDSTACK_VOLUME_TYPE:         replace-me
  BOSH_CLOUDSTACK_CONNECT_TIMEOUT:     replace-me
  BOSH_CLOUDSTACK_READ_TIMEOUT:        replace-me
  BOSH_CLOUDSTACK_WRITE_TIMEOUT:       replace-me
