---
name: concourse

# replace with bosh status --uuid
director_uuid: bc903999-bb89-48e1-b497-9de0236c38e0

# pick a sane db name and password
atc_db_name: &atc-db-name atc
atc_db_role: &atc-db-role
  name: atc
  password: egcivtoirj

# replace all addresses with your network's IP range
#
# e.g. X.X.0.2 -> 10.0.0.2
networks:
  - name: concourse
    type: manual
    subnets:
      - range: 192.168.117.0/24
        gateway: 192.168.117.254 
        dns: [10.203.6.102]
        reserved: 
        - 192.168.117.1 - 192.168.117.239
        - 192.168.117.245 - 192.168.117.253

        static:
          - &discovery_static_ip 192.168.117.240
        cloud_properties: {name: TRANSPARENT_NET }

releases:
  - name: concourse
    version: latest
  - name: garden-linux
    version: latest

jobs:
  - name: discovery
    instances: 1
    resource_pool: discovery
    persistent_disk: 1024
    templates:
      - {release: concourse, name: consul-agent}
    networks:
      - name: concourse
        static_ips: [*discovery_static_ip]
    properties:
      consul:
        agent:
          mode: server

  - name: web
    instances: 1
    resource_pool: web
    templates:
      - {release: concourse, name: consul-agent}
      - {release: concourse, name: tsa}
      - {release: concourse, name: atc}
    networks: [{name: concourse}]
    properties:
      atc:
        publicly_viewable: true
        basic_auth_username: atc
        basic_auth_password: athoncoz
        postgresql:
          database: *atc-db-name
          role: *atc-db-role

      tsa:
        atc:
          username: atc
          password: athoncoz


      consul:
        agent:
          servers: {lan: [*discovery_static_ip]}

  - name: db
    instances: 1
    resource_pool: databases
    persistent_disk_pool: database
    templates:
      - {release: concourse, name: consul-agent}
      - {release: concourse, name: postgresql}
    networks: [{name: concourse}]
    properties:
      postgresql:
        databases: [{name: *atc-db-name}]
        roles: [*atc-db-role]

      consul:
        agent:
          servers: {lan: [*discovery_static_ip]}

  - name: worker
    instances: 1
    resource_pool: workers
    templates:
      - {release: concourse, name: consul-agent}
      - {release: concourse, name: groundcrew}
      - {release: garden-linux, name: garden}
    networks: [{name: concourse}]
    properties:
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777

      consul:
        agent:
          servers: {lan: [*discovery_static_ip]}

disk_pools:
  - name: database
    disk_size: 10240
    cloud_properties:
      type: gp2

resource_pools:
  - name: web
    network: concourse
    stemcell: &stemcell
      name: bosh-cloudstack-xen-ubuntu
      version: latest
    cloud_properties:
      compute_offering: "CO1 - Small STD"    

  - name: discovery
    network: concourse
    stemcell: *stemcell
    cloud_properties:
      compute_offering: "CO1 - Small STD"    

  - name: databases
    network: concourse
    stemcell: *stemcell
    cloud_properties:
      compute_offering: "CO1 - Small STD"
      disk: 8192      
    
  - name: workers
    network: concourse
    stemcell: *stemcell
    cloud_properties:
      compute_offering: "CO1 - Small STD"
      disk: 8192
      ephemeral_disk_offering: "ephemeral"   

compilation:
  workers: 1
  network: concourse
  reuse_compilation_vms: true
  cloud_properties:
    compute_offering: "CO1 - Small STD"
    ephemeral_disk_offering: "ephemeral"

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
